### ISSUE TITLE
autocompletar CEP

### ISSUE THREAD

**Issue by alexandresoaresramos** [elisei/full-checkout#10]
Não sou desenvolvedor, apenas um user que faz algumas coisas em sua própria loja
Instalei o checkout e ta funcionando legal, mas não consegui mesmo fazer o CEP autocompletar
Precisaria de eu ter o modulo de autocompletar? isso que não entendi
M2.3.3p1 com tema porto
foi instalado pelo composer conforme wiki

segue uma demonstração em minha loja https://www.loom.com/share/f981afadcda943d89425de2fa58ac794

**Comment by elisei** [comment]
Oi @alexandresoaresramos 

Eu editei nossa sessão de suporte para melhor compreensão dos cenários de suporte prestados por nós. 

Por favor visite nossa [Wiki](https://github.com/elisei/full-checkout/wiki/Suporte) e sinta-se livre para reabrir esse issue e opinar sobre esse modelo que apresentamos e para que possamos buscar uma solução mais adequada a todos!

**Comment by elisei** [comment]
Oi @alexandresoaresramos  tudo bem?

Surgiu outro cliente com o mesmo problema, confirmar se em sua loja há o módulo BrazilCustomerAttributes

**Comment by alexandresoaresramos** [comment]
Como vai Bruno
Então eu até defini hoje cedo mandar reinstalar tudo do zero aqui pra ver
se era minha instalação

Não tinha essa extensão não
Após tiver pronto aqui está a sua disposição pra testes ok

Eu estou usando o 2.3.3p1
É compatível né?

Em sex, 26 de jun de 2020 13:11, Bruno <notifications@github.com> escreveu:
