### ISSUE TITLE
Checkout não habilita CPF

### ISSUE THREAD

**Issue by jrmaia** [elisei/full-checkout#11]
Fiz a instalação do módulo via composer em uma instalação limpa do magento 2.3 e após instalação o checkout não mostra o campo CPF.
Configurei os campos de endereço para 4, habilitei cpf e deixei como obrigatório.

Comando utilizados:

composer require o2ti/full-checkout
bin/magento setup:upgrade
bin/magento module:enable O2TI_FullCheckout
bin/magento setup:static-content:deploy -f
php bin/magento cache:clean

Magento versão 2.3.5-p1
Php 7.2.19
Tema: Padrão Luma

**Comment by o2ti** [comment]
Olá @jrmaia 

Essa configuração foi amplamente testada, por favor veja o tópico de configuração e persistindo o erro encaminhe um print por favor.

https://github.com/elisei/full-checkout/wiki/Configura%C3%A7%C3%B5es#em-lojas--configura%C3%A7%C3%B5es--cliente--configura%C3%A7%C3%B5es-de-cliente

**Comment by jrmaia** [comment]
Olá @o2ti obrigado pelo retorno, o problema estava nas configurações do magento.

Habilitei a opção: Stores > Configuration > Customer Configuration > Name and Address Options > Show Tax/VAT Number

Funcionou.

**Comment by o2ti** [comment]
@jrmaia 

Essa não é a configuração adequada, por favor veja o tópico indicado.
