### ISSUE TITLE
Erro no setup:upgrade

### ISSUE THREAD

**Issue by leonardosuporte** [elisei/full-checkout#12]
Prezado Elizei,

Estou usando o Magento 2.3.5-p1 e fiz a instalação do seu módulo full-checkout pelo composer e ativei o módulo.
Porém ao executar o setup:upgrade, apareceu esse erro:

`Invalid Document 
Element 'type', attribute 'disabled': The attribute 'disabled' is not allowed. Line: 14
Element 'type', attribute 'sortOrder': The attribute 'sortOrder' is not allowed. Line: 14`

Fiz uma pesquisa e vi que erro semelhante aconteceu com quem atualizou o Magento 2.1.* para o 2.2.*.
[https://github.com/magento/magento2/issues/11116](https://github.com/magento/magento2/issues/11116)

A solução que deram era retirar o atributo inválido, mas acho que isso irá quebrar o código do seu módulo.

Queria saber se você poderia me ajudar.
Obrigado pela atenção.

ps: um aviso que apareceu durante a instalação do módulo (pacotes depreciados):

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.`

**Comment by elisei** [comment]
Olá @leonardosuporte 

Nosso módulo não utiliza o sortOrder em block's.

Sobre o aviso, não é de uma dependência nossa sobre o pacote referido.

**Comment by leonardosuporte** [comment]
Prezado Elizei,

Queria saber qual a versão do Magento 2 que você usa com o seu módulo.
Obrigado pela atenção.

**Comment by RoninX2** [comment]
Também estou utilizando o magento 2.3.5 e estou com o mesmo erro que o Leonardo.

Invalid Document
Element 'type', attribute 'disabled': The attribute 'disabled' is not allowed.
Line: 14

Element 'type', attribute 'sortOrder': The attribute 'sortOrder' is not allowed.
Line: 14
 Quando tento acessar o site da error 500 (que é alguma coisa haver com o servidor)

**Comment by jboni** [comment]
Mesmo erro, comigo, vai fechar o tópico sem analisar?

**Comment by jboni** [comment]
Brasileiro tem muito que aprender com gringo, o bonitão da HAHA, prefere falar que o modulo ta bom e que 3 pessoas com o mesmo erro ta errada
se é na gringa como mage plaza pedem até acesso (free) p auxilar e trazer uma coisa boa p comunidade
Abraç haha
