### ISSUE TITLE
Erro no campo telefone

### ISSUE THREAD

**Issue by Marusso** [elisei/full-checkout#16]
Ao digitar o número do telefone/celular corretamente com ddd + numero, permanece uma mensagem dizendo que é necessário digitar um número com 14 dígitos.

Alguém sabe o que pode ser?

**Comment by LuizSantos1** [comment]
@Marusso Também tive esse problema, não sei se é o mesmo, mas ele não deixa digitar o último dígito do celular.
Não sei se é um problema do módulo de checkout ou do Magento. 
De momento, eu resolvi escondendo esse campo com o "hide" e deixei o campo "fax" para captar o número de celular ou fixo.
E coloquei essa informação editando o "label"...

Só que resolvi isso usando um módulo que possibilita a edição desses campos.

**Comment by LuizSantos1** [comment]
Não é o mesmo problema e eu também não resolvi. O campo de telefone fica sem me deixar inserir o nr de ceular... 
E acho que isso foi ocasionado pela instalação desse módulo que já desabilitei, mas deve ter criado alguma coisa no banco de dados que não conseguir achar...

**Comment by elisei** [comment]
@LuizSantos1 
Como pode ver no conteúdo do módulo ele não tem nenhum db_schema.xml ou mesmo diretório de Setup, em outras palavras, nada é feito em seu banco de dados.

@Marusso  Sobre o problema que reporta por favor verifique primeiro a sessão de suporte da Wiki do módulo, lá você encontrará orientações.

**Comment by Marusso** [comment]
Ola Elisei

Já revisei todas as configurações da Wiki, porem continuo com o problema ainda

![image](https://user-images.githubusercontent.com/16608158/90838307-f19dbe80-e32a-11ea-886a-e0706f62b73d.png)

**Comment by LuizSantos1** [comment]
> @LuizSantos1
> Como pode ver no conteúdo do módulo ele não tem nenhum db_schema.xml ou mesmo diretório de Setup, em outras palavras, nada é feito em seu banco de dados.

@elisei  Descobri que esse problema com a máscara vem do módulo BRAutocomplete, uma das empresas que desenvolveu esse módulo é a TechnoBR ou algo assim... 

Eles criaram esse módulo (BRAutocomplete) com preenchimento de endereço via CEP e com as máscaras de telefone, 
já para os campos CPF/CNPJ o módulo é o BRCustomer... 

Mas eles por algum motivo, limitam o formato no campo "telephone" em (99) 9999-9999 e não permite 
o formato (99) 99999-9999, este vai para o campo "cellphone" 

Isso gera dois problemas 
1 - O cliente que não tem telefone fixo, vai ficar tentando preencher o campo "telefone" como se fosse de celular,
e não vai conseguir. 
2 - Se colocarmos esse campo como "opcional" ou escondê-lo, como eu tentei, aí temos problemas com módulos
de pagamento como o do RicardoMartins-PagSeguro, que vai pedir para preencher esse campo que é obrigatório.

Se o seu módulo de alguma forma se baseou nesses módulos, ele terá os mesmos problemas no campo "telephone"
porque essa máscara tem esse bug. 

Acho que é por isso que vários clientes estão relatando o mesmo problema. 

Eu fui verificar se era o seu módulo, desistalei tudo e usei os módulos "BRAutocomplete" e "BRCustomer" para fazer a parte do autocompletar via CEP e tive o mesmo problema no campo "telephone"... 

Então se o seu módulo se baseia nele de alguma forma, retifique esse problema ou desabilite a máscara de telefone. 

Talvez você não consiga ver esse erro, porque não está usando um sistema de pagamento que exige o campo "telephone" original do Magento 2. Tente instalar o módulo do Ricardo Martins -Pagseguro, e você verá o problema. 

Att
Luiz Santos
