### ISSUE TITLE
Quebra de layout no meu tema

### ISSUE THREAD

**Issue by LuizSantos1** [elisei/full-checkout#19]
Oi, Elisei, tudo bem? 
Estou com um tema novo (Athlete2) e ele já tem um checkout bem rápido e bonito
Testei seu módulo novamente, ele funciona perfeitamente, até a questão das máscaras
de telefone, endereço e CPF rodaram limpas! Mas quebra muito o meu layout. 

Tem como deixar habilitado só a busca por CEP?
Queria desabilitar o resto, porque realmente gostaria de manter o layout e design original do tema.

Sei que não é um problema no seu módulo, mas peço mais como um favor como outra coisa,
já que outros clientes podem ter o mesmo problema no futuro. 

Att
Luiz Santos

**Comment by elisei** [comment]
Olá @LuizSantos1 

A finalidade desse módulo não é de uma busca de CEP, ou de implementação de máscara, ou mesmo validações extras, por isso não há opção de usar uma "parte" do módulo, esse módulo destina-se a ser uma solução completa de finalização para Magento 2, que entre outra coisas oferece tais funcionalidades.

Sugiro a contratação de um profissional para trabalhar em seu tema ou a escolha de um outro módulo de checkout.

**Comment by LuizSantos1** [comment]
@elisei Obrigado pela resposta. 
Meu problema dificilmente se resolveria com a contratação de um profissional, o tema "Athlete 2" para Magento 2, não é compatível com o seu plugin, nem entra na tela de checkout com ele habilitado. Daí de eu ter perguntado se seria possível instalar apenas a busca pela CEP. Contratar um profissional para desabilitar todas as customizações para que ele fique compatível apenas com um plugin, é totalmente inviável. 

Mas já resolvi o problema com o auxílio de 2 outros módulos. 

Att
Luiz Santos
