### ISSUE TITLE
Full-checkout tá pronto?

### ISSUE THREAD

**Issue by LuizSantos1** [elisei/full-checkout#2]
Olá, Elisei, tudo bem?
Sou um usuário seu do Moip Checkout Transparente (que já não funciona com a nova atualização de segurança do Magento)... Mas enfim, esse novo módulo funciona com o Magento 2 ou ainda não está pronto?

**Comment by elisei** [comment]
Olá @LuizSantos1 

Sim.

**Comment by LuizSantos1** [comment]
@elisei Legal, dê uma olhada lá na Wiki de instalação, está dando erro 404...

**Comment by LuizSantos1** [comment]
@elisei 
Como faço pra desistalar essa extensão?
Tou perguntando porque estou com um problema no sistema de pagamento da Picpay, e gostaria de
testar sem a sua extensão instalada para ver se é algum tipo de conflito.

Desde já, agradeço!

**Comment by LuizSantos1** [comment]
Olá, a versão antiga consegui instalar, a atual, o checkout está dando numa tela branca. Não aparece nada e nem log de erros.
Revisei a configuração e instalação duas vezes, está tudo instalado... Muito estranho.

Magento 2.3.5-p1
PHP 7.2.3 
Tema: Luma
