### ISSUE TITLE
Inverter campos de endereço

### ISSUE THREAD

**Issue by vcollina** [elisei/full-checkout#20]
É possível inverter as linhas 3 e 4 do endereço? Deixar 3 como complemento e 4 como bairro? Da forma como está acredito que seja incompatível com a maioria dos ERPs do mercado (ou pelo menos é incompatível com Bling e Tiny). Obrigado

**Comment by elisei** [comment]
Olá @vcollina 

Alterar o ordem de exibição no checkout não irá alterar como o Magento irá salvar os dados de street.

Os valores de street são exibidos como array de até 4 linhas, ao gravar a informação no banco de dados mesmo que o bairro esteja na posição 4 ao não ser preenchido o campo 3 (complemento) essa posição não será preservada ficando no banco de dados como rua, numero, bairro da mesma forma.

O que fazemos é no checkout ao exibir a informação trocamos a posição da linha 4 para visualmente estar após a posição da 2 (definida como número).

A única forma de tornar o bairro como fixo na posição 4 do endereço é tornando a posição 3 (complemento) como obrigatória, o que ao meu ver é um erro. Ou reescrevendo o módulo de gravação dos dados Magento.

**Comment by vcollina** [comment]
Então, mas o ERP faz o tratamento das posições já. Quando o endereço só tem 3 linhas, ele sabe que a linha 3 é bairro, não complemento. Quando tem 3 linhas, funciona normalmente. O problema é quando tem 4, aí inverte pq o módulo salva invertido.

Funcionaria normal se fosse salvo na ordem em que são exibidos e quando não tivesse complemento ficasse apenas três linhas. Isso é necessário para que o Magento não troque as posições? A pessoa compra uma vez e não preenche complemento, na segunda vez o bairro carregaria no campo complemento?

O que eu acho mais estranho é que aparentemente só eu uso o FullCheckout com Bling, pq o Bling também não tem como desinverter do lado deles.

**Comment by elisei** [comment]
@vcollina 

Versão 100.0.6 já corrigi isso! =)

**Comment by vcollina** [comment]
Opa, show Elisei!! Vc é o cara! Me tira uma dúvida, pelo que vi das alterações, entendo que o melhor seja eu dar um Truncate na tabela de endereços do Magento e zerar tudo, forçando os clientes a recadastrar o endereço. Vai dar problema com os endereços legados, certo? Exemplo, se a pessoa preencheu só Rua, Número e Bairro (antigas 1, 2 e 3), vai ter endereço que vai ficar sem bairro (agora 1, 2 e 4), pois o antigo bairro ficará no campo 3 complemento. Isso vai gerar erro na hora de finalizar a compra, sem o campo bairro a compra não finaliza. Está correto meu entendimento? Muito obrigado!!
