### ISSUE TITLE
Campos do endereço não abrem

### ISSUE THREAD

**Issue by vcollina** [elisei/full-checkout#22]
Temos recebido vez ou outra reclamações de clientes que não conseguem realizar a compra pois os campos de endereço não abrem. No checkout aparece apenas o CEP, a pessoa preenche, mas não carrega os demais como deveria. É algo recorrente, recebemos uma ou outra reclamação por semana, mas acredito que percentualmente seja muito pouco. Nunca consegui reproduzir esse erro aqui nem debuggar com os clientes, geralmente sugerimos comprar pelo PC e funciona. Alguém já enfrentou situação similar? Acredito que seja simplesmente uma falha de carregamento no celular, mas não conseguimos descobrir ainda.

**Comment by elisei** [comment]
Olá @vcollina 

Peguei esse erro também, já corrigi a 17 dias na versão 100.2.5 já publicada!

=)
