### ISSUE TITLE
reCAPTCHA falha na tela de login

### ISSUE THREAD

**Issue by andrebassumo** [elisei/full-checkout#23]
Bom dia Elisei, tudo bem? Estou tendo um problema com o recaptcha quando ativo "Enable for Customer Login" no magento 2.4 e o cliente já tem conta e vai logar no checkout apresenta erro. Teria como me ajudar? Att, André

**Comment by elisei** [comment]
Oi @andrebassumo 

Eu confirmo o issue, porém ainda não tive sucesso na tratativa dele, por hora recomendo desativar a opção de o "customer login". Mas estou trabalhando nesse problema e assim que possível retorno aqui. Por hora obrigado pelo reporte e me desculpe pelo erro!

**Comment by andrebassumo** [comment]
Imagina, eu quem agradeço o retorno, já desativei. Bom trabalho por aí....
e alias seus modulos tem sido bastante úteis. Até mais.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 9 de fev. de 2021 às 10:35, Bruno <notifications@github.com>
escreveu:

**Comment by alexandresoaresramos** [comment]
também com mesmo problema e aguardando...

**Comment by redati** [comment]
com recaptcha desabilitado veio uma chuva de pedidos spam ❌

**Comment by elisei** [comment]
Olá @redati  a sugestão é para desativar "apenas" o Enable for Customer Login. Os demais você pode manter.

Esse problema não é trato como prioridade, sintam-se fortemente encorajados a desenvolverem e partilhar em pull.

**Comment by redati** [comment]
Pelo que observei que o recapcha não é chamado em identify-step, estou tentando chegar no problema.

Adicionando no xml

<item name="recaptcha" xsi:type="array">
      <item name="component" xsi:type="string">Magento_ReCaptchaFrontendUi/js/reCaptcha</item>
      <item name="displayArea" xsi:type="string">additional-login-form-fields</item>
       <item name="configSource" xsi:type="string">checkoutConfig</item>
       <item name="reCaptchaId" xsi:type="string">recaptcha-checkout-login</item>
</item>

da um erro porque falta a configuração do recapcha vai javascript.

Então adicionando isso em module-re-captcha-checkout/Block/LayoutProcessor/Checkout/Onepage.php

$jsLayout['components']['checkout']['children']['steps']['children']['identify-step']
            ['children']['identify-by-email']['children']['recaptcha']['settings'] = $this->captchaUiConfigResolver->get($key);

O agora ele é inicializado. Porém o erro retornado ao fazer login é: "message: "Violação de segurança." Porém ainda não consigo  localizar a origem deste erro.

**Comment by redati** [comment]
isso resolveu  por enquanto >> https://gist.github.com/redati/7b9d116c12830c482b8d410e28148335

**Comment by elisei** [comment]
@redati Seu apoio foi fundamental! <3

Muito obrigado!
