### ISSUE TITLE
Frete não calculado, no caso de frete grátis. 

### ISSUE THREAD

**Issue by redati** [elisei/full-checkout#24]
Ótimo módulo, parabéns aos desenvolvedores. Espero algum dia contribuir também. 
Ainda estou aprendendo..

Em caso de valor de frete zerado, é exibido no resumo "Frete não calculado" (Isso já com a forma selecionada e na aba de pagamento já).  ao em vez de R$ 0,00 ou grátis.

Outra sugestão é deixar a logo com link para a home.

Abraços. 

Essa situação em 2.4.2.

**Comment by elisei** [comment]
Olá @redati 

Obrigado pelo issue, isso ajuda a melhorar o módulo e fico feliz que tenha gostado <3

O erro foi corrigido na versão 100.2.8 já publicada.

A quanto a solicitação de recurso, não é interessante implementar nesse momento, mas você pode personalizar em seu thema, facilmente, para conhecimento futuro vou deixar a orientação por aqui:

# Criar na pasta na atual pasta de seu  thema 

O2TI_FullCheckout/web/template/header 

Copiar o arquivo de nosso móudlo e editar.

**Comment by redati** [comment]
Legal.

Porém ainda ficou uma exceção.

No caso de retirada no local, o frete fica zerado, porém não é frete grátis.

Acredito que seria melhor exibir R$ 0,00.

Atualmente ficaria assim:

Retirada no local: Frete Grátis

**Comment by elisei** [comment]
Olá @redati 

Bom se o valor 0 é frete grátis. Mas entendo o seu lado no entanto acredito que perderíamos um recurso muito interessante para imensa maioria dos usuários embora as duas informações tenham o mesmo custo a percepção do cliente final é distinta por isso manterei o padrão se o valor 0 o frete é grátis.
