### ISSUE TITLE
Cancelamento de Newsletter

### ISSUE THREAD

**Issue by awakebrasil** [elisei/full-checkout#28]
Bom dia, 

todos os cliente que cadastram estão recebendo em seguida um e-mail de cancelamento da newsletter 

Você cancelou a sua assinatura da newsletter com sucesso. 

Como posso evitar isso? Obrigado.

**Comment by awakebrasil** [comment]
@elisei 

Realmente não entendi, utilizando o full-checkout preenche todos os campos perfeitamente a feita é feita OK, mas o cliente é cancelado na newsletter. estou vendo uma forma de colocar por default essa seleção de newsletter. 

Att...

**Comment by elisei** [comment]
Oi @awakebrasil ,

A 0 ocorrências para newsletter em nosso módulo, acredito que possa verificar se há algum personalização (ou módulo) conflitando. Por hora vou fechar o issue se houver mais detalhes por favor reabra! =)
