### ISSUE TITLE
magento 2.4.2 após logar ele da noroute

### ISSUE THREAD

**Issue by albertobraschi** [elisei/full-checkout#30]
Após efetuar o login no checkout, atualiza a pagina e da 404, no magento 2.4.2

**Comment by elisei** [comment]
Olá @albertobraschi  seu Magento está "limpo" sem outros módulo?

Pergunto isso pois rodo exatamente nessa versão e não consigo reproduzir esse erro, se possível envie o passo a passo para reproduzir.

**Comment by albertobraschi** [comment]
Ha varios outros modulos, incluindo pagamento e frete

**Comment by elisei** [comment]
Olá @albertobraschi 

Nós não temos como ajuda-lo sem uma descrição mais clara dos módulos que usa ou mesmo passo para reprodução do erro em um magento limpo.

Estou fechando o issue em função disso, caso possa prestar maiores informações, por favor reabra que certamente lhe apoiaremos na solução.
