### ISSUE TITLE
Problema com CEP

### ISSUE THREAD

**Issue by vcollina** [elisei/full-checkout#31]
Reabrindo #25 

Estou tendo esse problema com alguns clientes há algum tempo já também. Eu desabilitei o cálculo de frete no carrinho (display:none) em todos os campos e resolveu, mas uma ou outra pessoa ainda empaca nisso. Para reproduzir o erro, deve-se fazer o seguinte:

-Adicionar um produto ao carrinho
-Ir para a tela de checkout
-Digitar um CEP qualquer no FullCheckout
-Selecionar uma transportadora (importante!)
-Voltar para a tela do carrinho: nessa hora, o JS do magento vai recalcular o frete e vai zoar o CEP que está salvo. Mesmo com todos os campos ocultos, ele recalcula automático, não sei desabilitar isso
-Voltar para o FullCheckout

Nessa hora, duas coisas ocorrem: 1) o campo de seleção de transportadoras fica bloqueado (se tem duas, o cliente não consegue escolher) e 2) A compra não finaliza

A solução é o cliente apagar o CEP e digitar novamente, dessa forma desbloqueia as transportadoras e a compra finaliza

Segue print dos campos de frete bloqueados. Quando está assim, não vai concluir a compra.

Percebi aqui que se a pessoa já preencheu o endereço e depois volta para o site, adiciona ou troca algum produto no carrinho, o erro também acontece

![121692293-597deb00-ca9e-11eb-99f1-1590403630a8](https://user-images.githubusercontent.com/48520645/122087021-ab927980-cdda-11eb-95fa-cad48de5ca8f.png)

**Comment by elisei** [comment]
@vcollina Não tenho certeza se resolverá o seu problema, pois segundo sua descrição ele começa la no cart, no entanto agora se houver um cep digitado o endereço é exibido, se o cep for válido vai também buscar o endereço na base dados.
