### ISSUE TITLE
Limite Caracteres - Bairro

### ISSUE THREAD

**Issue by vcollina** [elisei/full-checkout#33]
Olá Bruno! Apenas uma sugestão para próx releases deste módulo que é o melhor de todos! :)

Não sei se está correta minha interpretação, mas acredito que a API do MOIP limita a quantidade de caracteres no campo bairro a 45:

https://docs.moip.com.br/reference#adicionar-cart%C3%A3o-de-cr%C3%A9dito

Como o limite no módulo está maior (Plugin/CheckoutLayoutPlugin.php - 255 de limite), vez ou outra algum cliente enche este campo de referências (casa amarela, portão branco, etc) e não consegue efetuar o pagamento. Sugestão seria limitar o campo a 45 caracteres para evitar o erro.

Obrigado e abraços!

**Comment by elisei** [comment]
@vcollina Muito obrigado, é bom ouvir que gosta! =)

Essa limitação foi implementada recentemente do lado da Moip https://github.com/wirecardBrasil/magento2/blob/Magento%402.4/Gateway/Request/AddressDataRequest.php#L121-L129

Já que é de lá que tem essa limitação é ela que deve fazer o tratamento. Por experiência acumulada no m1 onde faço isso no checkout posso dizer que tem alguns endereços, em especial os de Brasilia, que podem ficar errados no cadastro, por isso no m2 optei para travar no valor do limite imposto pelo bd e no módulo de pgto tratar para o limite que preciso! =)
