### ISSUE TITLE
Erro ao atualizar para versão mais recente 2.4.3-p1

### ISSUE THREAD

**Issue by redati** [elisei/full-checkout#35]
Fala amigo, beleza?

Parece haver um bug aqui.
https://github.com/elisei/full-checkout/blob/d045f88cdd15fb550c7d7aceaa020a519861dacd/view/frontend/web/template/form/field.html#L57

Estava dando erro no console e algumas coisas não funcionaram:
Found end comment without a matching opening comment, as child of [object Text]

Dei uma conferida e vi o erro sumiu após remover a tag  no final do arquivo view/frontend/web/template/form/field.html 

Aparentemente ela não deveria estar la, talvez tenha sido esquecida lá, ou ele fecha algum item de algum template pai? 

de qualquer forma, tudo funcionou após remover ela.

Abraço.

**Comment by elisei** [comment]
@redati :) valeu!!!!!!!! já aplicado já estará disponivel no packagist!

**Comment by elisei** [comment]
@redati oi!

Você consegue me chamar no privado tenho um possível trabalho para ti! (brunoelisei@o2ti.com)
