### ISSUE TITLE
Email Validation Error | Registered customers

### ISSUE THREAD

**Issue by corpsysgit** [elisei/full-checkout#36]
Há um erro de validação com o campo E-mail para clientes que tem contato no site.

Clientes que finalizam a compra como visitante, não há erros.

**Comment by corpsysgit** [comment]
![image](https://user-images.githubusercontent.com/15632329/150011366-64e65c45-243b-4728-be03-b6d1578cc00e.png)

**Comment by corpsysgit** [comment]
para clientes que tem cadastro* no site.

**Comment by elisei** [comment]
Olá @corpsysgit, tudo bem?

A informação que você vê é um retorno do método de pagamento e não do módulo de checkout. 

Se você utilizar outro módulo de checkout verá o mesmo comportamento.

**Comment by corpsysgit** [comment]
Mesmo utilizando forma de pagamento default do magento 2, ocorre erro semelhante.

![7CFF6650-F121-4E93-8476-30DCD11BA718](https://user-images.githubusercontent.com/15632329/150039531-3f13014c-65f5-4327-9d8e-b1c129e43e1a.jpeg)

**Comment by corpsysgit** [comment]
Resolvi o problema habilitando associação automática de clientes à um grupo.

![print error magento 2](https://user-images.githubusercontent.com/15632329/150422092-f31c40c7-fddf-418a-8394-3f402927a354.jpg)

**Comment by Marusso** [comment]
boa tarde pessoal,

@elisei 
passei por esse mesmo problema e seguir a solução do @corpsysgit realmente deu certo, porem não 100%, por exemplo:

No meu caso trabalho com grupos de clientes, tenho preços específicos para PF e PJ, ativando essa função, não consigo trabalhar dessa forma, o fluxo sempre vai puxar o preço de PF, então essa solução acabou sendo inviavel.

Porem notei que quando ela estava desabilitada, o processo seguia da forma que precisava, porem era barrado na finalização do pedido com a mensagem "**Failed address validation: Email has wrong format**". Cheguei a abrir um ticket na Pagar.me, porem não tive nenhum retorno sobre isso.

Após uma série de testes, eu desativei a opção do print abaixo e funcionou corretamente tudo como eu precisava
![checkout](https://user-images.githubusercontent.com/16608158/159774596-13e35784-fb3f-4809-b92f-66f1142a1cda.PNG)

Porem tem apenas mais um bug ao desativar essa opção, a parte direito do checkout some
![checkoutr](https://user-images.githubusercontent.com/16608158/159775009-e494f5f7-03a7-412f-b3cd-d0e408a8e2df.PNG)

OBS: Ja venho logado do carrinho para o checkout, pois devido algumas exigências do projeto, deve se logar antes de ir para o checkout

@elisei sabe me dizer por que some essa parte do checkout quando deixo o primeiro step desabilitado?

**Comment by elisei** [comment]
@Marusso 

Vamos a lá jack!

Primeiro, se precisa identificar o seu grupo de cliente é realmente necessário que ele se um cliente. Aqui então podemos definir, o "permite continuar como anonimo" como Não, assim o cliente acessa o checkout e ou é obrigado a criar uma conta ou é obrigado a logar-se!
![image](https://user-images.githubusercontent.com/1786389/159776291-15d4a8fa-0f6d-4bdb-9028-2ecd1820e49a.png)

(honestamente? se ele tem mudança de preço, ao acessar o site o cliente deveria ser logado!)

Segundo, "Failed address validation: Email has wrong format" sim isso erro deles (um deles, rs).

Terceiro, você diz o sidebar? (se for preciso debugar).

**Comment by Marusso** [comment]
@elisei 

Sim, me refiro ao sidebar.

No caso eu nao libero ele para se cadastrar no checkout, por que preciso de alguns campos personalizados como IE, e Razão Social. Eu cheguei a usar a própria função do modulo de adicionar novos campos, porem não tive sucesso, por isso mandamos eles para tela de cadastro antes de ir para o checkout.

Aparentemente eu notei que se essa opção de Identificação no Checkout esta desativada, o checkout não trás o sidebar

**Comment by Marusso** [comment]
@elisei 

Havia me esquecido de um ponto importante após desabilitar o step de identificação que seria os comandos upgrade e deploy, após isso funcionou corretamente

**Comment by corpsysgit** [comment]
@Marusso Obrigado pela contribuição. Tive o mesmo problema também na PagarMe.

@elisei desde o dia 17/03 agora tivemos problemas de validação de campos com a PagarMe, apresentando erro de não preenchimento de Rua, Bairro.. Na forma de pagamento Bank Transfer(Default no Magento2), funcionou normalmente.

Desde lá estou aguardando retorno do suporte deles..
