### ISSUE TITLE
Entrega para outro endereço não exibe no checkout

### ISSUE THREAD

**Issue by Marusso** [elisei/full-checkout#37]
Olá,

Quando seleciono no checkout para entregar em outro endereço na forma de pagamento, ele nao exibe os campos de endereço apra preencher.

Poderia me ajudar a entender o motivo?

Testei com o checkout padrão do Magento e aparece

Versão do magento 2.4.1
Versão do PHP 7.4

![image](https://user-images.githubusercontent.com/16608158/157684503-2518d531-d58a-4883-934e-ec36ebd7b798.png)

**Comment by elisei** [comment]
@Marusso 

Esse erro produzido em algum método de pagamento nativo?

**Comment by Marusso** [comment]
@elisei O erro acontece métodos nativo e de outros gateways também.

Esse do print por exemplo é da pgar.me, porem testei também com o Bank Transfer nativo e o Check / Money Order

Ambos acontece o mesmo problema.

**Comment by elisei** [comment]
@Marusso 

Ok, vou aprofundar os meus testes no entanto preliminarmente posso dizer que em tema nativo, com métodos nativos não ocorre.

**Comment by elisei** [comment]
@Marusso 

Não foi possível reproduzir esse erro em um Magento v2.4.3 com o tema Luma + Meios de Pagamento:
- Nativos
- Moip
- Getnet

Por favor, verifique seu ambiente se o problema é de origem de algum meio de pagamento ou mesmo da próprio tema usado.  Com isso poderei tentar apoia-lo na solução.

**Comment by Marusso** [comment]
@elisei Consegui descobrir o problema.

O tema utilizado no projeto possui um checkout customizado e ele estava sobrescrevendo algumas partes do FullCheckout, mesmo desabilitando o checkout pelo admin ele ainda sobrescrevia algumas partes.

Após desabilita-lo pelo setup:module disable e rodar o comando de deploy, ele passou a funcionar corretamente.

Obrigado pelo apoio prestado.

**Comment by elisei** [comment]
Valeu @Marusso!

Se possível, comente o tema usado e o módulo de checkout. Isso pode facilitar outros usuários a localizar e tratar problemas.

**Comment by Marusso** [comment]
@elisei Claro

Nome do tema: [Dukamarket - Multipurpose Responsive Magento 2 Theme](https://themeforest.net/item/dukamarket-multipurpose-responsive-magento-2-theme/31743563)
Módulo do checkout: É do próprio tema, chamado Rokanthemes_OnePageCheckout
