### ISSUE TITLE
CEP inválido para quem já tem cadastro e quer colocar novo endereço

### ISSUE THREAD

**Issue by corpsysgit** [elisei/full-checkout#38]
Checkout como visitante - OK
Checkout criando conta ao finalizar - OK
Checkout com conta já criada e endereço default - OK
Checkout com conta já criada e colocando endereço novo - ERRO

### Bug description
Ao finalizar o checkout já como cliente do site, com login efetuado, é mostrada uma mensagem de erro em vermelho solicitando o preenchimento do cep, porém o mesmo já está preenchido.

Mensagem de erro:
Por favor, especifique o cep no endereço de envio.

![ERRO NOVO ENDEREÇO](https://user-images.githubusercontent.com/15632329/158252050-f1ca3df1-3cf3-41cf-bdb1-233c6faf7e3e.png)

**Comment by elisei** [comment]
Olá @corpsysgit 

Por favor, descreva a versão do Magento e módulo que está usando e se possível se conseguiu reproduzir o erro em um magento "limpo".

**Comment by elisei** [comment]
@corpsysgit Estou fechando o issue por falta de interação. Caso necessário reabra.
