### ISSUE TITLE
Texto TESTE no menu minha conta (página cliente)

### ISSUE THREAD

**Issue by mauricio-tonny** [elisei/full-checkout#39]
Existe o texto TESTE antes do campo Estado na página minha conta sendo aplicado pelo módulo:

![BUG em MINHA CONTA](https://user-images.githubusercontent.com/68695691/159971402-3c19ffdd-2bb5-4451-8392-a7b3ba15343a.png)

Arquivo edit.phtml 

localizado em:

vendor/o2ti/advanced-street-address/view/frontend/templates/account/address 

![BUG IN CODE](https://user-images.githubusercontent.com/68695691/159971605-e3205caf-0b02-4197-b290-37a87b991f8f.png)

Após remover o texto, foi corrigido a questão

![CORRIGIDO](https://user-images.githubusercontent.com/68695691/159971747-991a9229-d09b-4e1e-9a92-754d86f7cbcf.png)

**Comment by elisei** [comment]
Olá @mauricio-tonny tudo bem?

Muito obrigado pelo repórter!

Você pode me dizer a versão do módulo que encontrou esse código por favor?

Esse é o módulo corrente
https://github.com/elisei/advanced-street-address/blob/Magento%402.4/view/frontend/templates/account/address/edit.phtml
