### ISSUE TITLE
{message: "Failed address validation:↵Email has a wrong format",…}

### ISSUE THREAD

**Issue by deciobezerra** [elisei/full-checkout#42]
Galera, estou finalizando um dev de uma loja, e estou enfrentando este problema no meu checkout, simplesmente ele não finaliza o pedido sempre gerando o erro de "email com formato inválido ", não sei se poderia ser alguma validação aqui deste módulo, alguém ja pegou este problema com o magento 2.4.3 p1?

**Comment by elisei** [comment]
Olá @decio-coder 

Dê uma olhada nesse issue:
https://github.com/elisei/full-checkout/issues/36

**Comment by deciobezerra** [comment]
@elisei muito obrigado, resolvi o problema com o set da configuração de clientes!!!! VALEU!!!!
