### ISSUE TITLE
Compatibilidade Amasty Social Login

### ISSUE THREAD

**Issue by corpsysgit** [elisei/full-checkout#43]
Temos já instalado o módulo Amasty Social Login, porém no seu checkout ele é mostrado na etapa 2, no momento de completar endereço.

Como movemos este bloco para a etapa 1? Como o social login do seu módulo.

Obrigado desde já.

**Comment by elisei** [comment]
Olá @corpsysgit 

Eu não sei, mas recomendo olhar na nossa estrutura como é feito:
https://github.com/elisei/social-login/blob/Magento%402.4/view/frontend/layout/checkout_index_index.xml

E faça algo semelhante por lá!

**Comment by corpsysgit** [comment]
Obrigado!
