### ISSUE TITLE
Failed to load the "O2TI_ThemeFullCheckout/shipping" template requested by "checkout.steps.shipping-step.shippingAddress".

### ISSUE THREAD

**Issue by corpsysgit** [elisei/full-checkout#44]
Olá, estou obtendo o seguinte erro ao iniciar checkout:

[ERROR] Failed to load the "O2TI_ThemeFullCheckout/shipping" template requested by "checkout.steps.shipping-step.shippingAddress".

![image](https://user-images.githubusercontent.com/15632329/197360983-42b6fe86-18cc-4978-9b19-7965b887e190.png)

Tela do checkout fica só carregando(com 2.4.4 funcionava perfeito com este template)
![image](https://user-images.githubusercontent.com/15632329/197360990-36d0835e-975f-40f4-93bb-affcb02bf9ba.png)

A versao do Magento que estou usando é a 2.4.5-p1

**Comment by elisei** [comment]
Olá @corpsysgit para abertura de issues é preciso realizar o teste em um ambiente limpo (sem personalizações, apenas a magento + o módulo). 

Você pode por favor realizar esse processo e caso o problema persista nos notificar?
