### ISSUE TITLE
Dúvida sobre os campos de endereço, na integração Clearsale

### ISSUE THREAD

**Issue by deciobezerra** [elisei/full-checkout#45]
Olá, surgiu uma dúvida devido a integração com a clearsale antifraude, a clear menciona na documentação deles os campos (street1, street2,street3,street4), ou seja Rua, Número, Complemento e Bairro, minha sequência utilizando o módulo O2TI- fullcheckout esta ok, porém o campo Rua, tem  a street como [street_0], e assim por diante com os outros campos, ou seja totalmente diferente do que  a clearsale pede e com isso surgem erros ao validarem a compra.
Seria possível alterar o campo [street_0], para [street_1]? não sei se expliquei corretamente!

**Comment by elisei** [comment]
Oi @decio-coder o street é um array, ele sempre irá começar como 0 (ou deveria).

Mas não acho que a clearsales esteja buscando o primeiro indice do array como array[1]. Por tanto acho que essa não é a causa raíz do problema.

**Comment by deciobezerra** [comment]
> Oi @decio-coder o street é um array, ele sempre irá começar como 0 (ou deveria).
> 
> Mas não acho que a clearsales esteja buscando o primeiro indice do array como array[1]. Por tanto acho que essa não é a causa raíz do problema.

@elisei muito obrigado pela informação, irei checar novamente!

**Comment by elisei** [comment]
qq coisa reabra aqui até para ajudar outros usuarios com a mesma dúvida! :)
