### ISSUE TITLE
Exibição do frete personalizado na finalização da compra!

### ISSUE THREAD

**Issue by deciobezerra** [elisei/full-checkout#46]
Olá @elisei tudo bem? Meu caro, eu tenho uma dúvida e gostaria de saber se poderia me ajudar com ela, estamos usando o full-checkout, na loja magento 2.4.3 e estamos com um problema em relação a finalizar pedidos. Para termos um frete competitivo, estamos utilizando um módulo chamado webshopapps matrix rate, ele monta um frete personalizado, onde a própria empresa se encarrega de realizar as entregas para seus clientes, até aqui ok.

Quando entramos na página de um produto qualquer e realizamos a consulta do frete, este frete personalizado é exibido na página do produto.. agora quando o cliente clica em finalizar o pedido e ele precisa efetuar login ou cadastro este frete não é exibido, o que é apresentado são somente os fretes 'Melhor Envio', o personalizado não é apresentado, poderia haver alguma relação com o checkout, a dúvida mesmo é se ja pegou algo do tipo em relação a frete personalizado utilizando o checkout full.

Um Abraço!

**Comment by elisei** [comment]
Oi @deciobezerra 

Nunca vi algum problema relacionado, mas muitos métodos diferentes integrados no full checkout, frenet, correios, melhor envio... Sugiro desativar o full checkout e ver se o frete aparece, aparecendo, analisar o código do módulo, possivelmente achará algum rewrite que no nosso módulo não é aplicado (ai é só desenvolvendo).

**Comment by deciobezerra** [comment]
@elisei obrigado, eu desativei o full-checkout e o problema permaneceu, teria algum módulo de frete personalizado que poderia indicar?

**Comment by elisei** [comment]
Olá @deciobezerra não conheço!
